### ISSUE TITLE
USAboundaries no longer exports us_boundaries()

### ISSUE THREAD

**Issue by program--** [mikejohnson51/AOI#18]
ropensci/USAboundaries@5c2aed38f64dc686011dc69327b6cab1d14b4844 describes this.

The `@importFrom` Roxygen tag (and consequently, the call in `NAMESPACE`) here: https://github.com/mikejohnson51/AOI/blob/421261e05d5b5979f2960adbec0ed172d6501b75/R/package_AOI.R#L41 causes the installation of `AOI` to fail, since it tries to load it.

**Comment by mikejohnson51** [comment]
Thanks @program-- looks like a definitive need for fipio!

**Comment by program--** [comment]
bec399e4baf9774b88ef5237037cd6dffe8b831c fixes this :smile:
