### ISSUE TITLE
Error: 'bbox_st' is not an exported object from 'namespace:AOI'

### ISSUE THREAD

**Issue by hjager** [mikejohnson51/AOI#20]
I am trying trying to avoid downloading the US/CONUS watershed boundaries by using a simple feature polygon for what we want to define as the MidAtlantic region as our AOI (different from what aoi_get returns with aoi('MidAtlantic')) with the following code:
> aoi.ma <- AOI::aoi_get(bbox.latlon)
> huc12.sf <- HydroData::findWBD(AOI=aoi.ma, level=12, subbasins=FALSE, crop=TRUE, ids=FALSE)
Error: 'bbox_st' is not an exported object from 'namespace:AOI'
In addition: Warning message:
In if (!(class(AOI) %in% c("list", "HydroData"))) { :
  the condition has length > 1 and only the first element will be used

Removing arguments from findWBD doesn't seem to help.

Ideas?  Thank you!
I was not able to use the AOI command from HydroData to export the polygon as an aoi object.  Have also tried adding some other arguments on findWBD, without success.

Yetta

**Comment by mikejohnson51** [comment]
Hi @hjager, I am so sorry i missed this! I moved most of HydroData's functionality into  https://github.com/DOI-USGS/nhdplusTools

An example for what you have above would be:

``` r
a = AOI::aoi_get("Fort Collins")
hucs = nhdplusTools::get_huc12(a) 
#> Spherical geometry (s2) switched off
#> although coordinates are longitude/latitude, st_intersects assumes that they
#> are planar
#> Spherical geometry (s2) switched on
plot(hucs$geometry)
plot(a$geometry, add = TRUE, border = "red", lwd = 2)
```

![](https://i.imgur.com/MW9aQad.png)

<sup>Created on 2022-12-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
