### ISSUE TITLE
aoi_get(country = "north america") does not return all of north america

### ISSUE THREAD

**Issue by rsmiller74** [mikejohnson51/AOI#23]
North America includes 3 primary countries - Canada, USA, and Mexico.  Greenland is typically considered a island country of North America.  If island countries are included than the Caribbean countries are also typically included.

> aoi <- aoi_get(country = "north america")
> 
> unique(aoi$admin)
[1] "Canada"                   "Greenland"                "United States of America"
>

**Comment by mikejohnson51** [comment]
Thanks @rsmiller74! This appears to be a bug. I will post here when it is fixed.

**Comment by mikejohnson51** [comment]
The culprit was two columns were being used to filter, one used `North America` while the other used `Northern America`

``` r
library(AOI)
aoi <- aoi_get(country = "north america")
unique(aoi$admin)
#>  [1] "The Bahamas"              "Belize"                  
#>  [3] "Canada"                   "Costa Rica"              
#>  [5] "Cuba"                     "Dominican Republic"      
#>  [7] "Greenland"                "Guatemala"               
#>  [9] "Honduras"                 "Haiti"                   
#> [11] "Jamaica"                  "Mexico"                  
#> [13] "Nicaragua"                "Panama"                  
#> [15] "Puerto Rico"              "El Salvador"             
#> [17] "Trinidad and Tobago"      "United States of America"
```

<sup>Created on 2022-12-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
