### ISSUE TITLE
Failure to install AOI

### ISSUE THREAD

**Issue by DorotheaDeus** [mikejohnson51/AOI#26]
i Mike,

I have been trying to install package AOI I am getting the message below, please assist, thank you in advance

"Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package ‘AOI’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Warning in CPL_crs_from_input(x) :
  GDAL Error 1: PROJ: proj_create: Non numerical value in towgs84 clause
Error in st_crs.character(projargs) : 
  invalid crs: +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0+no_defs
Error: unable to load R code in package ‘AOI’
Execution halted
ERROR: lazy loading failed for package ‘AOI’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/AOI’
Warning in install.packages :
  installation of package ‘/Users/dorothy/Downloads/AOI-0.1.0.tar.gz’ had non-zero exit status"

**Comment by mhweber** [comment]
Hi @mikejohnson51  - I seem to be getting an install error with AOI right now too-

        Downloading GitHub repo mikejohnson51/AOI@HEAD
        Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
        download from 'https://api.github.com/repos/mikejohnson51/AOI/tarball/HEAD' failed

**Comment by mhweber** [comment]
I think it was some Windows issue for me with utils::download.file - it wasn't working, I've updated everything on that machine, seems to be working now just fine.

**Comment by mikejohnson51** [comment]
Thanks @mhweber! I was out last week, but am back now. I will close this for now but if somethings else comes up please re-open!
